### ISSUE TITLE
Radio groups?

### ISSUE THREAD

**Issue by qrilka** [thaw-ui/thaw#102]
The example for `<Radio>` doesn't give any hint how I could arrange a radio group. Having just one radio button makes very little sense.

**Comment by luoxiaozero** [comment]
I'll add them in the future.

**Comment by qrilka** [comment]
Cool to see this resolved - any plans for a new release with these new additions @luoxiaozero ?

**Comment by qrilka** [comment]
Oh, I see 0.2.1, perfect!
