### ISSUE TITLE
Adjusting Modal width ?

### ISSUE THREAD

**Issue by glennpierce** [thaw-ui/thaw#108]
Hi I was wondering about changing the width of the Modal.
However, the question probably is more generic in that was is method for customising components.
I see Layout takes a style property. 
Should most components take this parameter ? Or are things like this intended to be changed by modifying global css ?

**Comment by luoxiaozero** [comment]
> Hi I was wondering about changing the width of the Modal.

I can add a width parameter to the Modal component.

> I see Layout takes a style property.
Should most components take this parameter ? Or are things like this intended to be changed by modifying global css ?

The reason for the style parameter is partly historical.  But I'm not averse to adding a style attribute to most components.

**Comment by carnego-git** [comment]
I probably only need the width. I can't think of anything else people would want to customise. Although having one property like style would make it easier for the user to know / remember api if it was something standard like style. Thanks

**Comment by glennpierce** [comment]
I probably only need the width. I can't think of anything else people would want to customise. Although having one property like style would make it easier for the user to know / remember api if it was something standard like style. Thanks
