### ISSUE TITLE
Drawer no longer close (head)

### ISSUE THREAD

**Issue by glennpierce** [thaw-ui/thaw#113]
Using git head the Drawer no longer closes on
pressing outside the drawer.

I think maybe on_after_leave has to also be on the fade transition but that is not the only issue
as the drawer still does not seem to close when is_lock is set to false.

**Comment by luoxiaozero** [comment]
Can you write a minimal repetition example?

**Comment by glennpierce** [comment]
Sure

https://github.com/glennpierce/thaw_testing

Contains a page with a drawer and popup.

The popup display small despite the width parameter.

Also when you open the drawer it stays open when clicking on the body of the page.

**Comment by luoxiaozero** [comment]
> The popup display small despite the width parameter.

https://github.com/glennpierce/thaw_testing/blob/1d59c048e4521b69ab7c085a33d1413cfc196893/src/pages/home.rs#L22
https://github.com/glennpierce/thaw_testing/blob/1d59c048e4521b69ab7c085a33d1413cfc196893/src/components/layout.rs#L31
Width parameter delete `;`, for example: `width="1200px"`

> Also when you open the drawer it stays open when clicking on the body of the page.

https://github.com/glennpierce/thaw_testing/blob/1d59c048e4521b69ab7c085a33d1413cfc196893/src/components/layout.rs#L18

You need to modify the placement parameter before opening the pop-up window. Change to:

```rust
    let open = Callback::new(move |new_placement: DrawerPlacement| {
        placement.set(new_placement);
        show.set(true);
    });
```

**Comment by glennpierce** [comment]
Thanks. 

The ; I left is was silly :( Sorry.

I'm surprised setting the show first effected the later hiding. That may rear its head again seems to expose the implementation detail to the api. Why does it fix it ?

**Comment by luoxiaozero** [comment]
This PR(#115) fixes the Drawer closing issue, but still requires you to change placement placement.
