### ISSUE TITLE
Select options z-index with modal / drawer

### ISSUE THREAD

**Issue by VincentBerthier** [thaw-ui/thaw#125]
Hi,
I’m trying to use a `Select` within a `Drawer` (same thing with a `Modal`).
The options however appear *behind* the Drawer which is less than optimal…
![image](https://github.com/thaw-ui/thaw/assets/34085617/d555c8a6-3b2b-48a4-9954-864846910a71)
(We only see a bit at the very bottom)
I’ve tried setting the `Select`’s z-index to 3000 but it doesn’t change anything (which I don’t think it can that way anyway?)

It works just fine with a standard html select:
![image](https://github.com/thaw-ui/thaw/assets/34085617/7d1e049d-55f0-4932-8f03-42ada886d6f2)

Am I missing something somewhere or is this a bug?

**Comment by luoxiaozero** [comment]
Setting the z_index attribute of the Drawer below 2000 should do the trick.

```rust
    <Drawer title="Title" show placement z_index=1999>
        <Select value options/>
    </Drawer>
```

**Comment by VincentBerthier** [comment]
It did indeed, thanks!
