### ISSUE TITLE
`icon` prop in `Button` does not accept a signal

### ISSUE THREAD

**Issue by tqwewe** [thaw-ui/thaw#130]
The `icon` prop in the `Button` component is of type `Option<icondata_core::Icon>`, which means it's not possible to change the icon based on a signal.

Is it possible for the `icon` prop use a signal instead?

**Comment by luoxiaozero** [comment]
Yes, I can change it to `Option<MaybeSignal<icondata_core::Icon>>`.

**Comment by tqwewe** [comment]
@luoxiaozero though if its `Option<MaybeSignal<icondata_core::Icon>>`, that means you cannot disable the button via a signal right?

Maybe `MaybeSignal<Option<icondata_core::Icon>>` would be better?
