### ISSUE TITLE
Add aling property to Space layout

### ISSUE THREAD

**Issue by fvacek** [thaw-ui/thaw#138]
![image](https://github.com/thaw-ui/thaw/assets/4949019/64f15a18-ed7b-4b1a-8e3b-0e78dec93f09)

I'm new to Thaw, so may be there is another way already. Also something like `flex-grow` would be nice.

**Comment by luoxiaozero** [comment]
Later, I'll implement the functionality in the image.

> Also something like flex-grow would be nice.

It doesn't feel like implementing something like `flex-grow` is easy.
