### ISSUE TITLE
Consider making components public ?

### ISSUE THREAD

**Issue by glennpierce** [thaw-ui/thaw#143]
Would you consider making

thaw::components public

I would like to copy the component Select so I can implement multiple item selection and do a few other custom things but with that private I cant access Binder of Follower which makes it difficult.

Could you suggest a better way if not ?

Thanks

**Comment by luoxiaozero** [comment]
I can distribute these components as separate libraries (thaw-components).

**Comment by glennpierce** [comment]
Great. 

the is also utils ie

```
thaw::utils::{class_list::class_list, mount_style, Model, OptionalProp};
```

Although perhaps I can work around those. Not sure .

Thanks

**Comment by luoxiaozero** [comment]
See https://crates.io/crates/thaw_components
