### ISSUE TITLE
Roadmap: v0.3

### ISSUE THREAD

**Issue by luoxiaozero** [thaw-ui/thaw#165]
(This supersedes the roadmaps in #114 .)

## Roadmap

[WAI-ARIA guidelines](https://www.w3.org/WAI/ARIA/apg/)

### component

* [x] Anchor component. #170
* [x] BackTop component. #169 
* [ ] Carousel component.
* [ ] Cascader component.
* [ ] Dropdown component.
* [ ] Multiselect component. #166 
* [ ] Pagination component.
* [ ] Popconfirm component.
* [ ] Popselect component.
* [ ] Rate component.
* [ ] Tree component.

---

Making a component library is a huge project, and I have limited time. Everyone is welcome to open PR or issue.

**Comment by bioinformatist** [comment]
@luoxiaozero Hey my bro, do you think it's necessary for adding new component who stands for "empty status"?

Just like: https://ant-design.antgroup.com/components/empty

I'm glad to submit a PR for it.

Besides, is there a discord channel for thaw?

**Comment by luoxiaozero** [comment]
> I'm glad to submit a PR for it.

Very welcome!

> Besides, is there a discord channel for thaw?

Not yet.

**Comment by luoxiaozero** [comment]
@bioinformatist I created a new discord channel.

https://discord.com/channels/1240583010978500638/1240583699796463669

**Comment by kandrelczyk** [comment]
@luoxiaozero I'm being kicked out of the discord server all the time. Any idea why?

**Comment by luoxiaozero** [comment]
@kandrelczyk I'm not very familiar with the Discord invite configuration, you can try the README Invite link.

**Comment by luoxiaozero** [comment]
@dmgolembiowski Some features needed by thaw are not yet implemented in the v0.7.0-preview2 version.  I am waiting for the release of leptosv-0.7.0-alpha.
