### ISSUE TITLE
need help ：is there way to change font-size of alert header and conent font size？

### ISSUE THREAD

**Issue by skydig** [thaw-ui/thaw#168]
I use following way to change font-size， but it does not work？
<Style>   
".thaw-alert__header{ font-weight: 400;font-size:0.875rem !important}"
    ".thaw-alert__content{ font-weight: 400;font-size:0.75rem !important}"
    </Style>

    <Alert variant=AlertVariant::Error title=alm.clone().objname class="thaw-alert__header thaw-alert__content" clone:alm >

**Comment by luoxiaozero** [comment]
Try it like this.

```rust
view! {
  <Style> ".my .thaw-alert__header{ font-weight: 400;font-size:0.875rem !important} .my .thaw-alert__content{ font-weight: 400;font-size:0.75rem !important}" </Style>
   <Alert
       variant=AlertVariant::Error
       title=alm.clone().objname
      class="my"
      clone:alm 
   />
}
```

**Comment by skydig** [comment]
thanks ,it works.
