### ISSUE TITLE
`Select` component's value should not be an `Option<T>`

### ISSUE THREAD

**Issue by tqwewe** [thaw-ui/thaw#171]
The Select component takes a `Model<Option<T>>` for the value. But this over complicates things in most cases, since there select would never have a `None` option. So the user needs to `.unwrap()` or match on the value every time they need to access it.

If the `Option` is removed, and user does in fact need a `None` option for their select, then they can make their own value be `Option<T>`, whilst the `Select` component itself doesn't need to care if the value uses an Option or not.

If you're happy with this change, I can implement it in https://github.com/thaw-ui/thaw/pull/166

**Comment by luoxiaozero** [comment]
I have implemented this feature in the v0.4-beta version.
