### ISSUE TITLE
Icon should be `display: inline-block`

### ISSUE THREAD

**Issue by tqwewe** [thaw-ui/thaw#172]
Since icons are typically used besides text or a label, it might make sense to add `display: inline-block`?

**Comment by luoxiaozero** [comment]
I feel that the behavior of Icon is the same as that of inline-block. Why add it? Can you give me an example?

**Comment by tqwewe** [comment]
I'm using tailwindcss in my project with Thaw, and the css reset for tailwind sets `svg { display: block; }`. But whenever I use Thaw icons, I always need to add `class="inline-block"` to fix the icons due to the reset. I'm quite sure many other people would use tailwind with Thaw and have the same issue

**Comment by luoxiaozero** [comment]
Understood, we can add `display: inline-block` to Icon.
