### ISSUE TITLE
`Button` with `Outline` variant should respect the `ButtonColor` prop

### ISSUE THREAD

**Issue by tqwewe** [thaw-ui/thaw#173]
The `ButtonColor` prop doesn't seem to work when using other variants such as `Outline`.

In the case of outline, the text color should perhaps be influenced by the button color prop. So `<Button variant=ButtonVariant::Outline color=ButtonColor::Primary>"Hello"</Button>` should have a blue text for the button.

A good example of this would be the official Thaw UI website's navigation not indicating the current page.

<img width="295" alt="Screenshot 2024-04-21 at 11 39 51 PM" src="https://github.com/thaw-ui/thaw/assets/16362377/a0f2d2f9-ef2a-4e09-a83b-918bd9c00e83">

*In the screenshot above, I'm on the Thaw UI "Guide" page, however the button does not indicate this. It would make sense for this to be blue as suggested in this issue.*

**Comment by luoxiaozero** [comment]
https://www.naiveui.com/en-US/os-theme/components/button#secondary.vue
https://www.naiveui.com/en-US/os-theme/components/button#quaternary.vue
Like this?

I feel that this will be a breakthrough change and we can implement it in 0.4. It won't be long, as lepots0.7-alpha should be released soon.

**Comment by luoxiaozero** [comment]
Given that the v0.4 release already follows the Fluent design specification, I'll close this issue.
