### ISSUE TITLE
datetime control will scroll(jump) to top when day or time selected

### ISSUE THREAD

**Issue by skydig** [thaw-ui/thaw#174]
how to avoid datetime control jump behavior as title described?

**Comment by luoxiaozero** [comment]
Currently, you cannot cancel the jump behavior. What scene do you need to cancel it?

**Comment by skydig** [comment]
thanks
scene is:
user click time, then time  component disappear(scroll up), she/he has to scroll to see it.

**Comment by luoxiaozero** [comment]
I fixed this issue at #180.
