### ISSUE TITLE
Default button should not be primary

### ISSUE THREAD

**Issue by tqwewe** [thaw-ui/thaw#181]
The default button variant seems to be `Primary`, however this isn't typically the most common button variant, and comparing with Pigment, Naive UI, and AntDesign, they all default to a more basic white button.

Additionally, I noticed that the default outlined button does not have a background color. Would it be preferred to have a background color for the default button similar to AntDesign and Pigment UI? This makes the most sense imo, since sometimes you might have a button over a slightly gray background, and want the button itself to be white, but there doesn't seem to be any way to add this without adding your own styles.

**Comment by luoxiaozero** [comment]
I feel more and more that Thaw needs a design language to guide it to avoid more problems like this in the future.

I'm currently bullish on [Fluent UI](https://fluent2.microsoft.design/). I want to make Thaw's design style tend to be Fluent UI in the future, but it doesn't have to be 100% similar.

**Comment by tqwewe** [comment]
Honestly, having a kind of port of Fluent UI to Leptos Rust would be so great imo. I feel a little that a lot of the values chosen for styles such as padding etc aren't too consistent in Thaw, whereas using something similar to Tailwind with fixed increments of sizings and such would give more consistency.

**Comment by luoxiaozero** [comment]
I have implemented this feature in the v0.4-beta version.
