### ISSUE TITLE
Message icon missalingment

### ISSUE THREAD

**Issue by dancixx** [thaw-ui/thaw#190]
Hi there,

there is an issue with message icon alignment as can be seen in the picture below.
<img width="261" alt="Képernyőfotó 2024-05-11 - 17 03 46" src="https://github.com/thaw-ui/thaw/assets/56868953/123a52a5-18da-4be8-9bb5-c6ce0f84bbdd">

Thanks for great work. :)

**Comment by luoxiaozero** [comment]
Can you provide an example of minimal repetition?

**Comment by kandrelczyk** [comment]
Hi, 

I've just submitted a PR with a fix proposal.
