### ISSUE TITLE
Theme mode should be done with classes/attributes

### ISSUE THREAD

**Issue by arturleao** [thaw-ui/thaw#192]
I'm trying to customize my light and dark theme and I'm having some trouble with it since it's all hardcoded and set into each component style.

I'm definitely not an UI expert but I believe it would be easier to override things if they were done using classes and maybe a light/dark attribute.

My main point of reference is Bootstrap where you have the attribute that define if it's light/dark and you can easily change it all very easily.

Thanks!

**Comment by luoxiaozero** [comment]
In thaw-v0.4.0-beta you can override the default theme by:

```
div.thaw-config-provider[data-thaw-id] {
    --colorBrandBackground: red;
    ...
}
```

Although you can override the default theme, I recommend using the following method to customize your theme:

```rust
let theme = RwSignal::new(Theme::light());
let on_customize_theme = move |_| {
    theme.update(|theme| {
        theme.color.color_brand_background = "#f5222d".to_string();
        theme.color.color_brand_background_hover = "#ff4d4f".to_string();
        theme.color.color_brand_background_pressed = "#cf1322".to_string();
    });
};

view! {
    <ConfigProvider theme>
        <Card>
            <Space>
                <Button appearance=ButtonAppearance::Primary on_click=move |_| theme.set(Theme::light())>"Light"</Button>
                <Button appearance=ButtonAppearance::Primary on_click=on_customize_theme>"Customize Theme"</Button>
            </Space>
        </Card>
    </ConfigProvider>
}
```
