### ISSUE TITLE
Allow label from Autocomplete to be any type that impl IntoView

### ISSUE THREAD

**Issue by heyjul** [thaw-ui/thaw#201]
Hi there, is there a reason why the label of the Autocomplete component only allow String and not any type that impl IntoView ? With this change, it would be possible to customize the options (like adding an image or whatever). I would be happy to make the change as I already did it for myself.

**Comment by luoxiaozero** [comment]
> Hi there, is there a reason why the label of the Autocomplete component only allow String and not any type that impl IntoView ?

This is a problem left over from history.

> I would be happy to make the change as I already did it for myself.

Very welcome.

**Comment by heyjul** [comment]
Can't think of a way to implement this without breaking changes.
