### ISSUE TITLE
Layout component issue

### ISSUE THREAD

**Issue by GISerliang** [thaw-ui/thaw#204]
I used Layout component to show something. Sometimes I got an error like this.
![image](https://github.com/thaw-ui/thaw/assets/11342604/9059de35-7998-49fb-8935-a4b55042a7e1)

**Comment by luoxiaozero** [comment]
I solved it in v0.3.3, can you try it and see if there is still this problem?

**Comment by GISerliang** [comment]
> I solved it in v0.3.3, can you try it and see if there is still this problem?

I tested it and found no problems for now.
