### ISSUE TITLE
Select does not support groups.

### ISSUE THREAD

**Issue by otopetrik** [thaw-ui/thaw#222]
It looks like it is not possible to group values in Select/MultiSelect ([optgroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup)).
In addition to "group" field, structures SelectOption/MultiSelectOption should probably also have "disabled" field.

**Comment by luoxiaozero** [comment]
​Adding these features in v0.3 is a breaking change, I will implement it in v0.4 ([thaw-fluent](https://github.com/thaw-ui/thaw/tree/thaw/fluent)) .

**Comment by luoxiaozero** [comment]
I have implemented this feature in the v0.4-beta version.
