### ISSUE TITLE
Thaw Demo looks broken on Linux: system fonts are not used

### ISSUE THREAD

**Issue by jploz** [thaw-ui/thaw#231]
When using thaw's main branch (fluentui/v0.4) on Linux a fallback font rather than the system font is used for rendering. This looks different than what was rendered using thaw-v0.3 and does not match the system user interface. It looks bad and out of place.

Reason for this change in v0.4 is that generic font-families are missing in the definition of the theme: ui-sans-serif, system-ui and ui-monospace.

This patch fixes this and restores the look from v0.3 and what I would expect (on Linux):

```
diff --git a/thaw/src/theme/common.rs b/thaw/src/theme/common.rs
index fa460f6..18ad053 100644
--- a/thaw/src/theme/common.rs
+++ b/thaw/src/theme/common.rs
@@ -68,9 +68,9 @@ pub struct CommonTheme {
 impl CommonTheme {
     pub fn new() -> Self {
         Self {
-            font_family_base: "'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif".into(),
-            font_family_monospace: "Consolas, 'Courier New', Courier, monospace".into(),
-            font_family_numeric: "Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif".into(),
+            font_family_base: "'Segoe UI', 'Segoe UI Web (West European)', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif".into(),
+            font_family_monospace: "Consolas, ui-monospace, 'Courier New', Courier, monospace".into(),
+            font_family_numeric: "Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif".into(),
 
             font_size_base_100: "10px".into(),
             font_size_base_200: "12px".into(),
```

Notable is, that Firefox (which I use) does actually not support `ui-*`, only `system-ui` is supported.

I've not prepared a PR but only above patch, HTH.

**Comment by luoxiaozero** [comment]
Since version 0.4 is a complete rewrite, I prefer to use Fluent's design style.

I suggest you can use a custom theme:

```rust 
let mut theme = Theme::light();
theme.common.font_family_base = "'Segoe UI', 'Segoe UI Web (West European)', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif".into();
theme.common.font_family_monospace =  "Consolas, ui-monospace, 'Courier New', Courier, monospace".into();
theme.common.font_family_numeric = "Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif".into();
let theme = RwSignal::new(theme);

view! {
    <ConfigProvider theme>
          "..."
    </ConfigProvider>
}
```

**Comment by jploz** [comment]
Thanks for the reply. I haven't approach the issue from this side actually. I understand that you want to stick to the defintions from fluentui.

For future references I want to share some collected links and information around the topic *"Fonts and Fluent design v9"*:

**fluentui**

> Fluent UI web represents a collection of utilities, React components, and web components for building web applications. 

The repository is located here: https://github.com/microsoft/fluentui
An overview of react components can be found here: https://react.fluentui.dev/

**Font family as defined in Fluent design v9**

```
fontFamilyBase
'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif
fontFamilyMonospace
Consolas, 'Courier New', Courier, monospace
fontFamilyNumeric
Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif
```
see https://react.fluentui.dev/?path=/docs/theme-fonts--docs#font-family

**Fonts used on https://react.fluentui.dev**

The website https://react.fluentui.dev actually uses Segoe UI as font also on Linux. It loads the fonts from a Microsoft CDN https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.woff2

How is this possible?

> All files on the Fluent UI React GitHub repository are subject to the MIT license. Please read the License file at the root of the project.
>
> Usage of the fonts and icons referenced in Fluent UI React is subject to the terms of the [assets license agreement](https://aka.ms/fluentui-assets-license).

In this assets license Microsoft provides a restricted license for the Segoe font

>  for the following purposes:
> a. In connection with the use of a Microsoft API within the development of a software
>  application, website, or product you create or a service you offer designed to provide access
>  or interact with a Microsoft service or application (“Application”)
> b. To illustrate that Application integrates with one or more Microsoft products and services.

Generally, Segoe fonts are not distributable for other purposes (as web font, bundled with apps etc.) without a license (see https://learn.microsoft.com/en-us/typography/fonts/font-faq):

> No, as Segoe UI is both our user interface and corporate branding font, it is not available for use outside of Microsoft products on non-Windows platforms.

The primary monospace font (`Bahnschrift`) has the same issues.

**Open questions**

What I find a bit concerning is, that the Fluent design guide prefers *proprietary* fonts which are not freely available and distributable as primary fonts. On macs it will fallback to the Apple system font, however the font definition does not include a sensible default for Linux systems (which would be `system-ui`).

One can workaround that limitations using a custom theme and/or importing the `Roboto` font in the `index.html`. This is ok and works for me.

What remains is, that the *thaw demo* using the v0.4 branch on Linux looks bad and broken. For this reason it might be good to select defaults which work well on all platforms (in particular since the design guide is mainly driven by Microsoft and does not cater all platforms well).

**Comment by luoxiaozero** [comment]
First of all, thank you for asking this question.  I had not noticed the font restrictions of Fluent UI before.

I don't know enough about font restrictions. Do I need to remove the proprietary fonts(Segoe UI, Bahnschrift) from the fonts to circumvent Microsoft's font restrictions?

Also, for issues in Linux, I'm willing to add `ui-*` and `system-ui` to solve.
