### ISSUE TITLE
missing attrs on Checkbox, Combobox and possibly few other components

### ISSUE THREAD

**Issue by ataraxia3** [thaw-ui/thaw#233]
I'm currently using an uncontrolled Checkbox inside a form, but can't set the `attr:name` property needed when calling server functions.
Having `attr:name` on Combobox would also be convenient when dealing with forms
Maybe related [feat/input-attrs](https://github.com/thaw-ui/thaw/pull/65)

**Comment by luoxiaozero** [comment]
I’ll add the Field component to solve this problem.

**Comment by luoxiaozero** [comment]
I added id and name attributes to the Checkbox and Combobox components.  You can also use the [Field](https://thawui.vercel.app/components/field) component.
