### ISSUE TITLE
The demo breaks on scrolling

### ISSUE THREAD

**Issue by amiyatulu** [thaw-ui/thaw#237]
RuntimeError when scrolled in the demo.

https://thawui.vercel.app

This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! [button](https://thawui.vercel.app/components/button)
Uncaught RuntimeError: unreachable executed

**Comment by luoxiaozero** [comment]
Can you post the steps to reproduce?

**Comment by amiyatulu** [comment]
Its happening in the desktop not mobile, when one drag the left scroll bar.

**Comment by luoxiaozero** [comment]
I fixed it here. https://github.com/thaw-ui/thaw/pull/238
