### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by zouhangyu** [thaw-ui/thaw#26]
|
443 | enum SignalTypes<T>
    |      ^^^^^^^^^^^
note: required because it appears within the type `Signal<T>`
   --> C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\leptos_reactive-0.5.2\src\signal_wrappers_read.rs:76:12
    |
76  | pub struct Signal<T>
    |            ^^^^^^
note: required because it appears within the type `StoredMaybeSignal<T>`
   --> C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\thaw-0.1.1\src\utils\stored_maybe_signal.rs:4:10
    |
4   | pub enum StoredMaybeSignal<T>
    |          ^^^^^^^^^^^^^^^^^
note: required because it's used within this closure
   --> C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\thaw-0.1.1\src\input_number\mod.rs:41:15
    |
41  |     let sub = move |_| {
    |               ^^^^^^^^
    = note: required for `leptos::Callback<MouseEvent>` to implement `From<{closure@C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\thaw-0.1.1\src\input_number\mod.rs:41:15: 41:23}>`
    = note: required for `{closure@C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\thaw-0.1.1\src\input_number\mod.rs:41:15: 41:23}` to implement `Into<leptos::Callback<MouseEvent>>`
note: required by a bound in `ButtonPropsBuilder::<(__style, __variant, __color, __round, __icon, __loading, __disabled, (), __children)>::on_click`
   --> C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\thaw-0.1.1\src\button\mod.rs:58:1
    |
58  | #[component]
    | ^^^^^^^^^^^^ required by this bound in `ButtonPropsBuilder::<(__style, __variant, __color, __round, __icon, __loading, __disabled, (), __children)>::on_click`
...
67  |     #[prop(optional, into)] on_click: Option<Callback<ev::MouseEvent>>,
    |                             -------- required by a bound in this associated function
    = note: this error originates in the derive macro `::leptos::typed_builder_macro::TypedBuilder` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `thaw` (lib) due to 7 previous errors

windows 10 leptos 0.5.2

any ideas?

**Comment by luoxiaozero** [comment]
I have no problems running on my windows, can you provide the rust version and the steps to reproduce?

**Comment by zouhangyu** [comment]
i put thaw into my project,and vscode gives this:
![image](https://github.com/thaw-ui/thaw/assets/152187462/9ad0c2ca-3ef6-4883-b4e4-fe5c446455da)

cargo.html under dir app is:
[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }
http.workspace = true
cfg-if.workspace = true
thiserror.workspace = true
serde = { version = "1", features = ["derive"] }
tracing.workspace = true
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "tls-rustls",
    "sqlite",
], optional = true }

tokio = { workspace = true, features = ["full"], optional = true }
thaw = { path = "../thaw", features = ["hydrate", "ssr"] }
[features]
default = ["csr"]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr", "thaw/csr"]
hydrate = [
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate",
    "thaw/hydrate",
]
ssr = [
    "dep:tokio",
    "dep:sqlx",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:leptos_axum",
    "thaw/ssr",
]

sorry,i am a beginer in rust and leptos. thanks for your help.

另外如果是中国人，我就回中文了

**Comment by liborw** [comment]
Same here on linux,

way to reproduce:
```
cargo init thaw_test
cargo add leptos --features=csr,nightly
cargo add thaw
rustup override set nightly
trunk serve
```

The result:
```
...
error[E0277]: the trait bound `(dyn std::ops::Fn() -> T + 'static): callback::NotRawCallback` is not satisfied in `{closure@/home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/input_number/mod.rs:41:15: 41:23}`
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/input_number/mod.rs:44:5
    |
41  |       let sub = move |_| {
    |                 -------- within this `{closure@/home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/input_number/mod.rs:41:15: 41:23}`
...
44  | /     view! {
45  | |         <Input value=input_value allow_value placeholder>
46  | |             <InputSuffix slot>
47  | |                 <Button variant=ButtonVariant::Link on_click=sub>
    | |                                                     -------- --- this tail expression is of type `{closure@mod.rs:41:15}`
    | |                                                     |
    | |                                                     required by a bound introduced by this call
...   |
54  | |         </Input>
55  | |     }
    | |_____^ within `{closure@/home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/input_number/mod.rs:41:15: 41:23}`, the trait `callback::NotRawCallback` is not implemented for `(dyn std::ops::Fn() -> T + 'static)`
    |
note: required because it appears within the type `PhantomData<dyn Fn() -> T>`
   --> /home/****/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/marker.rs:809:12
    |
809 | pub struct PhantomData<T: ?Sized>;
    |            ^^^^^^^^^^^
note: required because it appears within the type `Unique<dyn Fn() -> T>`
   --> /home/****/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/unique.rs:37:12
    |
37  | pub struct Unique<T: ?Sized> {
    |            ^^^^^^
note: required because it appears within the type `Box<dyn Fn() -> T>`
   --> /home/****/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:195:12
    |
195 | pub struct Box<
    |            ^^^
note: required because it appears within the type `PhantomData<Box<dyn Fn() -> T>>`
   --> /home/****/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/marker.rs:809:12
    |
809 | pub struct PhantomData<T: ?Sized>;
    |            ^^^^^^^^^^^
note: required because it appears within the type `StoredValue<Box<dyn Fn() -> T>>`
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.3/src/stored_value.rs:24:12
    |
24  | pub struct StoredValue<T>
    |            ^^^^^^^^^^^
note: required because it appears within the type `SignalTypes<T>`
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.3/src/signal_wrappers_read.rs:444:6
    |
444 | enum SignalTypes<T>
    |      ^^^^^^^^^^^
note: required because it appears within the type `Signal<T>`
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.3/src/signal_wrappers_read.rs:77:12
    |
77  | pub struct Signal<T>
    |            ^^^^^^
note: required because it appears within the type `StoredMaybeSignal<T>`
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/utils/stored_maybe_signal.rs:4:10
    |
4   | pub enum StoredMaybeSignal<T>
    |          ^^^^^^^^^^^^^^^^^
note: required because it's used within this closure
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/input_number/mod.rs:41:15
    |
41  |     let sub = move |_| {
    |               ^^^^^^^^
    = note: required for `leptos::Callback<MouseEvent>` to implement `From<{closure@/home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/input_number/mod.rs:41:15: 41:23}>`
    = note: required for `{closure@/home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/input_number/mod.rs:41:15: 41:23}` to implement `Into<leptos::Callback<MouseEvent>>`
note: required by a bound in `ButtonPropsBuilder::<(__style, __variant, __color, __round, __icon, __loading, __disabled, (), __children)>::on_click`
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thaw-0.1.1/src/button/mod.rs:58:1
    |
58  | #[component]
    | ^^^^^^^^^^^^ required by this bound in `ButtonPropsBuilder::<(__style, __variant, __color, __round, __icon, __loading, __disabled, (), __children)>::on_click`
...
67  |     #[prop(optional, into)] on_click: Option<Callback<ev::MouseEvent>>,
    |                             -------- required by a bound in this associated function
    = note: this error originates in the derive macro `::leptos::typed_builder_macro::TypedBuilder` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `thaw` (lib) due to 7 previous errors
```

Cargo.toml:
```
[package]
name = "learn-thaw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.3", features = ["csr", "nightly"] }
thaw = "0.1.1"
```

```
❯ cargo -Vv
cargo 1.76.0-nightly (9b13310ca 2023-11-24)
release: 1.76.0-nightly
commit-hash: 9b13310ca596020a737aaa47daa4ed9ff8898a2f
commit-date: 2023-11-24
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Linux Rolling Release [64-bit]
````

**Comment by luoxiaozero** [comment]
Yes, this is only an issue when leptos turns on the nightly feature at nightly.  I'll fix it as soon as possible.

**Comment by luoxiaozero** [comment]
@zouhangyu  可以说中文，我知道问题的原因了，我会尽快修复。你可以取消 leptos 的 nightly feature 或者把 rust 切换到 stable 版本来临时解决这个问题。

> tokio = { workspace = true, features = ["full"], optional = true }
> thaw = { path = "../thaw", features = ["hydrate", "ssr"] }
> [features]

另外这里 thaw 不能同时开启 hydrate, ssr, csr（有csr 的原因是默认开启它，所以不写，也会有），只能同一时间使用一个。

**Comment by luoxiaozero** [comment]
I have fixed this problem in the main branch. But did not fundamentally solve the problem, specific can see https://github.com/leptos-rs/leptos/issues/2041 .
