### ISSUE TITLE
Implement From<(Signal, SignalSetter)> for thaw_utils::Model

### ISSUE THREAD

**Issue by dsche** [thaw-ui/thaw#271]
Consider the following use case:

```
let data: RwSignal<ComplexData> = ...;
let property_slice = slice!(data.property); // slice has type (Signal<T>, SignalSetter<T>)
...

view! {
<AutoComplete value=property_slice ... />
}
```
This will not work (at least not with `0.3.x`), as the second component of the `property_slice` tuple is not `WriteSignal<T>`. This is kind of unfortunate and mandates constructing more boilerplate code to work around this restriction. Would it make sense to implement `From<(Signal, SignalSetter)>` for `thaw_utils::Model`?

**Comment by luoxiaozero** [comment]
I think it makes sense, I will add this `From<(Signal, SignalSetter)>`.

**Comment by dsche** [comment]
A proposal is in #280, comments are welcome :-)
