### ISSUE TITLE
Reactive Tracking Error

### ISSUE THREAD

**Issue by laskinner** [thaw-ui/thaw#281]
Found after upgrading to 0.7.0-gamma2 and 0.4.0-beta3 (via git)

This error immediately shows up in compilation after including thaw in cargo.toml.

![thaw_error](https://github.com/user-attachments/assets/ef0e9631-f021-43f7-ac5e-1efea8ae07ab)

**Comment by laskinner** [comment]
this week I'll see if I can get around to reproducing in a new repo and send the link. Is that what you're after?

**Comment by luoxiaozero** [comment]
Yes, because I didn't reproduce this problem on my computer.

**Comment by MikhailNazarov** [comment]
I get this error when add thaw like this:
```
thaw = { version = "0.4.0-beta4", features = ["ssr", "hydrate", "nightly"] }
```

but if i write:
```
thaw = { version = "0.4.0-beta4", features = ["nightly"] }
```
error is gone

**Comment by luoxiaozero** [comment]
@MikhailNazarov The ssr feature and the hydrate feature cannot be enabled at the same time. If you use cargo-leptos , you can refer to this: https://thawui.vercel.app/guide/server-sider-rendering

**Comment by MikhailNazarov** [comment]
@luoxiaozero , thank you for reply. I'm using cargo-leptos. Could I specify following?

```
[features]
default = ["thaw/nightly"]
hydrate = ["leptos/hydrate", "thaw/hydrate"]
ssr = [
    "dep:axum",
    "dep:tokio",
    "dep:tower",
    "dep:tower-http",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:tracing",
    "thaw/ssr",
]

```
@luoxiaozero , could I specify following

```
[features]
default = ["thaw/nightly"]
hydrate = ["leptos/hydrate", "thaw/hydrate"]
ssr = [
    "dep:axum",
    "dep:tokio",
    "dep:tower",
    "dep:tower-http",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:tracing",
    "thaw/ssr",
]

```
It seems to work that way.

**Comment by luoxiaozero** [comment]
@MikhailNazarov Does your leptos dependency have the `nightly` feature enabled? If so, you can remove `default = ["thaw/nightly"]` and change the thaw dependency to `thaw = { version = ..., features = ["nightly"] }`

**Comment by laskinner** [comment]
I was able to get it to compile and run.

I tinkered with settings, and this runs:

leptos = { version = "=0.7.0-rc1", features = ["nightly"]}
thaw = { git = "https://github.com/thaw-ui/thaw", features = ["ssr", "nightly"] }
[features]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = [
  "dep:actix-files",
  "dep:actix-web",
  "dep:leptos_actix",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "thaw/ssr",
]


@luoxiaozero I think this can closed.
