### ISSUE TITLE
Srollbar elements in the way of styling a layout

### ISSUE THREAD

**Issue by ydirson** [thaw-ui/thaw#286]
I'm a bit confused as to how I can make a Layout fill its parent block.  My component hierarchy is like `<Layout><LayoutHeader>...</LayoutHeader><Flex>...</Flex></Layout>`.
I have set `min-height: 100vh` on the outermost element generated by the layout (`.thaw-layout`), and FF inspector shows it has expected height.  But then the `flex` element deep within all 3 levels of `thaw-scrollbar*` elements just takes the minimum height for its contents.  It seems really clunky to compute a  `min-height` for the Flex by finding out the header height to substracting it from 100vh, so I may be missing something.
I'm also not very sure of what those `thaw-scrollbar*` elements brings over standard CSS `scroll` stuff.

Still with FF inspector, I can get the result I want by:
- removing those 3 layers of scrollbar elements
- setting `display: flex; flex-direction: column` on the `.thaw-layout`
- setting `flex:1` on the `thaw-flex`

This seems to confirm the source of the difficulty lies in the presence of those scrollbar elements.  How can we improve the situation?

**Comment by luoxiaozero** [comment]
You can use `content_style` or `content_class` to solve this problem. For example:

```html
<Layout content_style="min-height: 100vh; display: flex; flex-direction: column">
      <LayoutHeader>"…"</LayoutHeader>
      <Flex style="flex: 1">"…"</Flex>
</Layout>
```

or

```html
<Layout content_class="...">
      <LayoutHeader>"…"</LayoutHeader>
      <Flex class="...">"…"</Flex>
</Layout>
```

**Comment by ydirson** [comment]
That's perfect, thanks much!
