### ISSUE TITLE
Massive CSS Duplication in SSR

### ISSUE THREAD

**Issue by Jazzpirate** [thaw-ui/thaw#328]
When using SSR, every instance of a component injects its CSS in the header again - e.g. when using, say, 10 `<Badge>` nodes on a page, the header will contain 10 `<style id="thaw-id-badge">` nodes, unnecessarily bloating the resulting HTML.

A potential solution could be to use a context value in SSR to store css ids to avoid duplication.

**Comment by luoxiaozero** [comment]
Refer to the `examples/ssr_axum/src/app.rs` file in https://github.com/thaw-ui/thaw/pull/335/commits/266dd6dd4a75484501cd8936429669221c1d4ee1. Wrap the `html` tag with the `SSRMountStyleProvider` component.
