### ISSUE TITLE
Feature Request: Make components compatible with MathML

### ISSUE THREAD

**Issue by Jazzpirate** [thaw-ui/thaw#329]
For a project I'm working on, I wanted to have Popups on MathML nodes. Currently, Popover (and possibly/likely other components?) always use `<div>` nodes as wrappers for the trigger, which breaks if the trigger occurs in a MathML node. I therefore had to copy-paste your implementation of Popovers and patch it to selectively use `<mrow>` instead.
Annoyingly, I then realized that I had to *also* copy the `Binder` component, since it has a trait guard `E::Output: Deref<Target = web_sys::HtmlElement>` (and MathML nodes are not `HtmlElement`). It seems that restriction can be weakened to `E::Output: Deref<Target = web_sys::Element>` (which MathML nodes implement), since it only seems to be necessary for calls to `get_bounding_client_rect`, which only requires `Element`.

My solution was for `Popover` to take an optional `DivOrMrow` implemented as
```
pub enum DivOrMrow {
    #[default]
    Div,
    Mrow,
}
```
with corresponding enums for NodeRefs, Elements etc.

If you're interested, I could open a pull request

**Comment by luoxiaozero** [comment]
I changed the child type of `PopoverTrigger` to be generic in #329. Now you can do:

```rust
view! {
    <math display="block">
        <mfrac>
            <Popover>
                <PopoverTrigger slot>
                    <mrow>
                        <mn>"1"</mn>
                        <mo>"+"</mo>
                        <mi>"K"</mi>
                    </mrow>
                </PopoverTrigger>
                "Content 1 + k"
            </Popover>
        </mfrac>
    </math>
}
```

**Comment by Jazzpirate** [comment]
Awesome :) One thing that confuses me though is:
in https://github.com/thaw-ui/thaw/blob/f82d8a3b6dcd55a27408778ac4d1c79e4e472344/thaw/src/popover/mod.rs#L44 you still use a `NodeRef<Div>` and attach that to the child of the trigger - that looks like it should break if that child is not a `div`-node...?

**Comment by luoxiaozero** [comment]
It’s so strange, now it can work even if it’s not a div node. 

I will improve this.

**Comment by Jazzpirate** [comment]
Huh, interesting - maybe leptos doesn't actually check that the tag matches when setting the NodeRef signal...? (I assume usually it should match by construction, when used as a `node_ref=`-attribute, so...)
