### ISSUE TITLE
Simple example for ssr_axum and island cases are missed..

### ISSUE THREAD

**Issue by rgr-1** [thaw-ui/thaw#332]
### The problem
1. **examples/ssr_axum** contains whole Demo app which is not very helpful for someone who want to start with small thingy.

2. **examples/island:**  
  - as of now is not compilable. One need to add correct `log module` usage in `examples/island/src/main.rs`
  - and then button click is not operational - i.e. there is no reactivity in the app 
  - and then there is nothing from Thaw in there. I.e. there is no any active element from Thaw in this example
  - and if Thaw elements added they are not operational - see next

3. if one follow  **examples/ssr_axum** readme and create own project then
 - any inserted Thaw component is functional, but doesn't have styles. I.e. **slider is invisible**, spinner is ugly, button is also no beautiful. 
![2024-12-02_18-44](https://github.com/user-attachments/assets/53738e2f-709a-4655-9f74-f82c4e85b757)

### The wish 
1. It would be very helpful to have minimal working example(s) containing actual Thaw component (i.e. slider) for ssr (and island) case.
2. Also it would be very helpful if this demo would use Thaw as external dependency i.e. `thaw = { git = "https://github.com/thaw-ui/thaw", branch = "main"}`

**Comment by luoxiaozero** [comment]
> examples/ssr_axum contains whole Demo app which is not very helpful for someone who want to start with small thingy.

I think I can add some repositories like [start-axum](https://github.com/leptos-rs/start-axum) which might help.

> examples/island:

Because of my energy problem, I will not consider compatibility with island in the short term.

> any inserted Thaw component is functional, but doesn't have styles. I.e. slider is invisible, spinner is ugly, button is also no beautiful.

Are you using the ConfigProvider component at the root of your component?

**Comment by rgr-1** [comment]
> I think I can add some repositories like [start-axum](https://github.com/leptos-rs/start-axum) which might help.

This one I used as start point. It does work, however Thaw is not part of it. The whole idea is to jump on this Thaw train with all these nice component. The Demo app looks very very attractive indeed.    

> Because of my energy problem, I will not consider compatibility with island in the short term.

Understandable and completely rightful. It might be useful to have one line in readme file about the sample status..

> Are you using the ConfigProvider component at the root of your component?

Yes I do. However it was Demo app dissection which lead me to this before rising the hand. With ConfigProvider I was able to see the proper styling for a moment on reload and then all is gone. 

It would be enormously beneficial to have some sort of doc or guide for newcomers. Or as said before the minimal app with Thaw component(s). Sure all above might be very clear to others with relevant experience, but for newcomers like me it's a bit of mystery.

**Comment by rgr-1** [comment]
just in case - this is what I see on the page. 
For sure I miss something in my small app -  as Demo app shows in its beauty.. 
![image](https://github.com/user-attachments/assets/d25f24f3-e026-4606-bec1-a5bce534552a)

**Comment by luoxiaozero** [comment]
> For sure I miss something in my small app - as Demo app shows in its beauty..

Can you share your code?

**Comment by rgr-1** [comment]
Sorted this one out. 
it was Cargo.toml with `thaw = { ..., features = ["ssr"] }` based on [this](https://thawui.vercel.app/guide/server-sider-rendering). Removing this option did the trick. I.e. it's not exactly clear that **cargo-leptos** section  is not "**and** do this in addition to above".
Also I need to get better with the basics. My understanding was that ssr implies hydration.. as otherwise how one could make "things change" on pre-rendered page.  

I will close this one. 
Plus I will propose ssr_axum_minimum example a bit later. To help someone like me. 

And thanks again for beautiful components :)
