### ISSUE TITLE
Popover with click trigger type stay open 

### ISSUE THREAD

**Issue by geovie** [thaw-ui/thaw#333]
Hi, first thanks for this crate it's really nice to use.

One thing I noticed is that using the click trigger type on popups will keep them open when another popup trigger is clicked.

I guess the issue comes from:
https://github.com/thaw-ui/thaw/blob/main/thaw/src/popover/mod.rs#L135
where the event propagation is stopped on click which prevents the other popups from closing themselves
https://github.com/thaw-ui/thaw/blob/main/thaw/src/popover/mod.rs#L122

To reproduce simply add mulitple popups with trigger type click on the same page and click on the triggers

**Comment by luoxiaozero** [comment]
Thank you for reporting this bug.
