### ISSUE TITLE
`<Select>` component doesn't work with SSR

### ISSUE THREAD

**Issue by maccesch** [thaw-ui/thaw#49]
It panics here: https://github.com/thaw-ui/thaw/blob/08936c92ffd03bfdf1825d2b62e19e53e8617acd/src/select/mod.rs#L27

**Comment by luoxiaozero** [comment]
I tried an example [examples/ssr_axum](https://github.com/thaw-ui/thaw/tree/main/examples/ssr_axum) .
1. rust stable, leptos stable
2. rust nightly, leptos stable
3. rust nightly, leptos nightly feature

No problem.

Can you provide the rust version and the steps to reproduce?

**Comment by luoxiaozero** [comment]
I will close this issue, if there are any questions please reopen or open a new issue.
