### ISSUE TITLE
Tab component documentation incorrect -wrong string

### ISSUE THREAD

**Issue by 0atman** [thaw-ui/thaw#50]
The [Tabs](https://thaw-ui.github.io/thaw/components/tabs) component has a non-compiling example, though the data presented in the table below it is correct:

```rust
    let val = create_rw_signal("apple");  // <- this is a &str, not a String
    view! {
        <Tabs value=val>
            <Tab key="apple" label="Apple">
                "apple"
            </Tab>
            <Tab key="pear" label="Pear">
                "pear"
            </Tab>
        </Tabs>
    }

```

The signal must be a `String`, or it gives this error:

```rust
error[E0277]: the trait bound `RwSignal<std::string::String>: From<RwSignal<&str>>` is not satisfied
  --> src/main.rs:15:5
```

The example project is correct: https://github.com/thaw-ui/thaw/blob/main/demo/src/pages/tabs/mod.rs#L8

Can the docs be built from the compiling examples, perhaps with Rustdoc?

**Comment by luoxiaozero** [comment]
This is a documentation error and I will fix it later.  

> Can the docs be built from the compiling examples, perhaps with Rustdoc?

Good idea, maybe write a runtime macro (get the code from the demo or from the code comments) and generate both the running code and the code text.
