### ISSUE TITLE
report ssr csr error?

### ISSUE THREAD

**Issue by skydig** [thaw-ui/thaw#76]
my cargo.toml report following error.  why? thanks!!!!!

cargo leptos build --release app
then run app
......
[DANGER] You have both `csr` and `ssr` or `hydrate` and `ssr` enabled as features, which may cause issues like <Suspense
/>` failing to work silently.

if I remove thaw from toml and source code, DANGER disappear..

cargo.toml is as following:
[package]
name = "info_demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
lto = true

[dependencies]
console_log = "1.0.0"
console_error_panic_hook = "0.1.7"
cfg-if = "1.0.0"
leptos = { version="0.5.4", features = ["nightly"] }
leptos_axum = { version="0.5.4", optional = true }
leptos_meta = { version="0.5.4", features = ["nightly"] }
leptos_router = { version="0.5.4", features = ["nightly"] }
leptos-struct-table = { version="0.6.0", features = ["chrono"] }
chrono = { version = "0.4", features=["serde"] }
async-trait = "0.1"
log = "0.4.17"
simple_logger = "4.0.0"
serde = { version = "1.0.148", features = ["derive"] }
tracing = "0.1"
gloo-net = { version = "0.2.5", features = ["http"] }
reqwest = { version = "0.11.13", features = ["json"] }
axum = { version = "0.6.1", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4", features = ["fs"], optional = true }
tokio = { version = "1.22.0", features = ["full"], optional = true }
http = { version = "0.2.11", optional = true }
web-sys = { version = "0.3", features = ["AbortController", "AbortSignal","CanvasRenderingContext2d","HtmlCanvasElement"] }
wasm-bindgen = "0.2"
#thaw = { version="*", features = ["ssr"]}
thaw = {git="https://github.com/thaw-ui/thaw.git",branch="main"}
plotters = "^0.3.2"
wee_alloc = "0.4.5"
plotters-canvas = "^0.3.0"
rand = "0.8"
leptos_server_signal = "*"

[features]
default = ["csr"]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
  "dep:axum",
  "dep:tower",
  "dep:tower-http",
  "dep:tokio",
  "dep:http",
  "leptos/ssr",
  "thaw/ssr",
  "leptos_axum",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "leptos_server_signal/ssr",
  "leptos_server_signal/axum", # or actix
]

[package.metadata.cargo-all-features]
denylist = ["axum", "tower", "tower-http", "tokio", "http", "leptos_axum"]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "info_demo_axum"
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site"
# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"
# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site-root>/<site-pkg>/app.css
style-file = "./style.css"
# [Optional] Files in the asset-dir will be copied to the site-root directory
assets-dir = "public"
# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site-addr = "127.0.0.1:3000"
# The port to use for automatic reload monitoring
reload-port = 3001
# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
end2end-cmd = "npx playwright test"
#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"
# Set by cargo-leptos watch when building with tha tool. Controls whether autoreload JS will be included in the head
watch = false
# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"
# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
#
# Optional. Defaults to false.
bin-default-features = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
#
# Optional. Defaults to false.
lib-default-features = false

**Comment by luoxiaozero** [comment]
If there are any more questions

> [features]
> default = ["csr"]
> csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
> hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
> ssr = [
> "dep:axum",
> "dep:tower",
> "dep:tower-http",
> "dep:tokio",
> "dep:http",
> "leptos/ssr",
> "thaw/ssr",
> "leptos_axum",
> "leptos_meta/ssr",
> "leptos_router/ssr",
> "leptos_server_signal/ssr",
> "leptos_server_signal/axum", # or actix
> ]

Try changing the above configuration to

```toml
[features]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr", "thaw/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate", "thaw/hydrate"]
ssr = [
    "dep:axum",
    "dep:tower",
    "dep:tower-http",
    "dep:tokio",
    "dep:http",
    "leptos/ssr",
    "thaw/ssr",
    "leptos_axum",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "leptos_server_signal/ssr",
    "leptos_server_signal/axum", # or actix
]
```

**Comment by skydig** [comment]
I modified sourcecode as your suggestion, error disappeared, 

thank!
