### ISSUE TITLE
select shrink to empty when use space?

### ISSUE THREAD

**Issue by skydig** [thaw-ui/thaw#79]
code is as following	
![image](https://github.com/thaw-ui/thaw/assets/27293515/2b6e0c5e-e45b-4c86-8f6d-e797182c5e0b)
select menu like following picture
![image](https://github.com/thaw-ui/thaw/assets/27293515/db448f34-0cd0-4eec-b822-115bd3a2b176)

**Comment by luoxiaozero** [comment]
Hi, your information is not complete. ( code or picture )

**Comment by skydig** [comment]
code is as following	
          ```
 <Space>
            "class"
            <Select value=s_value options/>
            </Space>
```

**Comment by skydig** [comment]
> Hi, your information is not complete. ( code or picture )

I have updated

**Comment by skydig** [comment]
yes， it works when using class prop,
thanks,
