### ISSUE TITLE
how to change thaw component text size?

### ISSUE THREAD

**Issue by skydig** [thaw-ui/thaw#85]
![image](https://github.com/thaw-ui/thaw/assets/27293515/4c2393e5-5ae1-4e24-95eb-ead8646331af)
like above picture,
how can I  change calendar font size just like 2024-01-17(smaller) which I have modified using class?
thanks.

**Comment by luoxiaozero** [comment]
If you want to change the popup style of all date picker components, you can add a class to override it.

If you want to change only the popup style of the specified date picker component, I can add a popup_class attribute to the date picker component.

**Comment by skydig** [comment]
the quick solution is to" change the popup style of all date picker components", could you give me a class override example? I can try it. 
thanks in advance.

**Comment by luoxiaozero** [comment]
Add the following classes.

```css
.thaw-date-picker-panel {
    font-size: 12px;
}
```

**Comment by skydig** [comment]
![image](https://github.com/thaw-ui/thaw/assets/27293515/bb07a18f-a74e-4ed4-b075-5707785bc496)
it really can work, but the panel position is strange just live above picture.

and date panel can work too, the panel can appear but disappear quickly and date can not be selected?

**Comment by luoxiaozero** [comment]
Try it like this.

```html
<Style>
".font-normal { font-weight: 400; font-size: 0.75rem; }"
".thaw-time-picker-panel, .thaw-date-picker-panel { font-size: 0.75rem; }"
</Style>
"date"
<DatePicker class="font-normal" value=date_value/>
"time"
<TimePicker class="font-normal" value=time_value />
```

**Comment by skydig** [comment]
> Try it like this.
> 
> ```
> <Style>
> ".font-normal { font-weight: 400; font-size: 0.75rem; }"
> ".thaw-time-picker-panel, .thaw-date-picker-panel { font-size: 0.75rem; }"
> </Style>
> "date"
> <DatePicker class="font-normal" value=date_value/>
> "time"
> <TimePicker class="font-normal" value=time_value />
> ```

thanks，it really work, I don't know why it's class="font-normal", but it really work,

sorry again,
I add button color class as follwing picture, but why the button color keep as default(not changed)?
			```
  ".thaw-time-picker-panel, .thaw-date-picker-panel { font-size: 0.75rem; }"
				  ".thaw-button {background-color:#04AA6D;}"
				  <Button  class="thaw-button">"next"</Button>
```

**Comment by luoxiaozero** [comment]
There should be a style overlay because of css priority.

**Comment by skydig** [comment]
> There should be style overwriting due to css priority issues.

is there temporary solution?

**Comment by luoxiaozero** [comment]
> I add button color class as follwing picture, but why the button color keep as default(not changed)?

Try this.

```rust
<Style>
".my-button.thaw-button { background-color: #04AA6D; }"
</Style>
<Button class="my-button">"next"</Button>
```

**Comment by skydig** [comment]
splendid! all you solution can work
thanks!
