### ISSUE TITLE
Drawer feature requests ?

### ISSUE THREAD

**Issue by carnego-git** [thaw-ui/thaw#96]
1, Drawers should only place within its parent component.
So I can have one overall page drawer but a smaller one in a div 

2, Allow not fulling closing so to can hover to expand. Saves the consumer of the control having to create a button for display.

3, css animate the expansion.

Thanks

**Comment by luoxiaozero** [comment]
I'll implement 1 and 3 later.

> 2, Allow not fulling closing so to can hover to expand. Saves the consumer of the control having to create a button for display.

I don't think this should be implemented by a component library. But I'd like to hear your ideas, such as implementation ideas.

**Comment by glennpierce** [comment]
> I'll implement 1 and 3 later.
> 
> > 2, Allow not fulling closing so to can hover to expand. Saves the consumer of the control having to create a button for display.
> 
> I don't think this should be implemented by a component library. But I'd like to hear your ideas, such as implementation ideas.

After having time to think about this I think you are right. Probably too niche of a feature.

**Comment by carnego-git** [comment]
I probably only need the width. I can't think of anything else people would want to customise. Although having one property like style would make it easier for the user to know / remember api if it was something standard like style. Thanks
